# Development docker environment
# To run this file, use the command:
# docker-compose -f docker-compose-dev.yaml up --build
version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile.dev
    ports:
      - 3000:6000
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    volumes:
      - ./src:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0